import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import "animate.css"

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
